{
 "title": "tech_challenge_2_monitoring_dashboard",
 "description": "Dashboard de monitoramento da API criado para o Tech Challenge 2(FIAP)\nGrupo 15",
 "tags": [
  "fiap_tech_challenge",
  "grupo_15"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(up,job)" } },
   {
    "name": "request_path",
    "label": "Endpoint",
    "query": {
     "query": "label_values(http_requests_info_total_count{job=\"$job\"},path)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Serviços Monitorados",
   "type": "stat",
   "description": "Resumo do status dos serviços monitorados",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Detalhes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "description": "Status do serviço monitorado",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"$job\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tempo de funcionamento",
     "type": "stat",
     "description": "Último tempo de funcionamento registrado pela API",
     "gridPos": { "h": 5, "w": 12, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - process_start_time_seconds{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Status",
     "type": "timeseries",
     "description": "Histórico do status da API por tempo",
     "gridPos": { "h": 7, "w": 20, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bool" } },
     "targets": [
      {
       "expr": "up{job=\"$job\"}",
       "legendFormat": "Status - API"
      }
     ]
    }
   ]
  },
  {
   "title": "Recursos Máquina",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "gauge",
     "description": "Percentual de utilização do CPU pela API",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "system_runtime_cpu_usage{job=\"$job\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Histórico de utilização de CPU",
     "type": "timeseries",
     "description": "Histórico de utilização de CPU pela API por tempo",
     "gridPos": { "h": 6, "w": 12, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "system_runtime_cpu_usage{job=\"$job\"}",
       "legendFormat": "Uso de CPU"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "gauge",
     "description": "Uso da memória pela API(em bytes)",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_private_memory_bytes{job=\"$job\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Histórico de utilização de RAM",
     "type": "timeseries",
     "description": "Histórico de utilização de RAM pela API(em bytes)",
     "gridPos": { "h": 6, "w": 12, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "process_private_memory_bytes{job=\"$job\"}",
       "legendFormat": "Uso de memória"
      }
     ]
    }
   ]
  },
  {
   "title": "Requisições",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total de Requisições",
     "type": "stat",
     "description": "Número total de requisições recebidas pela API",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_requests_info_total_count{job=~\"$job\", path=~\"$request_path\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tempo médio das requisições",
     "type": "bargauge",
     "description": "Média de tempo(em segundos) que as requisições estão levando na API",
     "gridPos": { "h": 7, "w": 17, "x": 3, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_requests_info_total_sum{job=~\"$job\", path=~\"$request_path\"}) by (path)  / sum(http_requests_info_total_count{job=~\"$job\", path=~\"$request_path\"}) by (path)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Status de resposta das requisições",
     "type": "timeseries",
     "description": "Resumo dos status de resposta da API para as requisições durante o período selecionado",
     "gridPos": { "h": 9, "w": 13, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum by(request_status) (round(increase(http_requests_info_total_count{job=~\"$job\"}[$__range])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requisições por status de resposta",
     "type": "piechart",
     "description": "Contagem de requisições por status de resposta(http status)",
     "gridPos": { "h": 9, "w": 7, "x": 13, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_requests_info_total_count{job=~\"$job\", path=~\"$request_path\"}) by (request_status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requisições por endpoint",
     "type": "bargauge",
     "description": "Número de requisições recebidas por endpoint",
     "gridPos": { "h": 11, "w": 13, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(path) (http_requests_info_total_count{job=~\"$job\", path=~\"$request_path\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Status das Requisições",
     "type": "bargauge",
     "description": "Resumo dos status de retorno(HttpStatus) retornados pela API",
     "gridPos": { "h": 11, "w": 7, "x": 13, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_requests_info_total_count{job=~\"$job\", path=~\"$request_path\"}) by (request_status, path)",
       "legendFormat": "{{path}} - {{request_status}}"
      }
     ]
    }
   ]
  }
 ]
}