services:
  prometheus:
    image: prom/prometheus:v2.24.1
    container_name: prometheus
    volumes:
     - ../prometheus/settings/:/etc/prometheus/
    ports:
     - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
      - ../grafana/settings/dashboard_setup.json:/etc/grafana/provisioning/dashboards/imported-dashboards/dashboard.json
      - ../grafana/settings/prometheus-datasource.yml:/etc/grafana/provisioning/datasources/prometheus-datasource.yml
      - ../grafana/settings/grafana-dashboard.yml:/etc/grafana/provisioning/dashboards/grafana-dashboard.yml
    ports:
     - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring


    
networks:
  monitoring:
    driver: bridge