# RabbitMQ: Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: tc3
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: fiaptech3acr.azurecr.io/rabbitmq:latest
        ports:
        - containerPort: 5672
        - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: tc3
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service-management
  namespace: tc3
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 80
      targetPort: 15672
  type: ClusterIP
