apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: services-ingress
  namespace: tc3
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
        - path: /GetContacts
          pathType: Prefix
          backend:
            service:
              name: get-contacs-service
              port:
                number: 80
    - http:
      paths:
      - path: /metrics/getcontacts
        pathType: Prefix
        backend:
          service:
            name: get-contacs-service
            port:
              number: 80
    - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-service
            port:
              number: 9090