apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: services-ingress
  namespace: PLACEHOLDER_NAMESPACE
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
        - path: /GetContacts
          pathType: Prefix
          backend:
            service:
              name: get-contacts-service
              port:
                number: 80